### ISSUE TITLE
missing default value?

### ISSUE THREAD

**Issue by rgkirch** [funcool/lentes#15]
```clojure
(lens/over (lens/in [:path] ["default"])
           #(conj % "hi")
           {})
```
returns `{:path ("hi")}` but I expect `{:path ["default" "hi"]}`

I would expect the default value to get passed into the update function. Is the above how it's supposed to work?

**Comment by niwinz** [comment]
This is the expected behavior, the `in` lens is defined as:

```clojure
(lens (fn [s] (get-in s path default))
      (fn [s f] (update-in s path f)))))
```
This means, getter and setter are individual options, and update-in does not define the default.

If you want, the default value used also for updates, you probably need something like this:

```clojure
(lens (fn [s] (get-in s path default))
      (fn [s f] (update-in s path (fnil f default))))))
```

**Comment by rgkirch** [comment]
Thanks. What's the rationale? Does it break any lens laws? I'm a total novice and there's plenty of information available regarding this but I didn't want to leave you hanging. I appreciate your response and I've had great success using the library so far.

**Comment by niwinz** [comment]
No, it does not breaks any law I think, but in any case; maybe this is an expected behavior from one perspectvie, can be unexpected from other. If you define a getter with default value, the setter is not expected to execute the getter, they are separated operations. In any case. The `builtin` **in** lense is just an implementation; it is not mandatory to you use it. You should create your own lenses for your purposes.

**Comment by rgkirch** [comment]
Ok, thank you. I was trying too hard to get by with just the provided lenses.
