### ISSUE TITLE
IEquiv for RWFocus?

### ISSUE THREAD

**Issue by ghost** [funcool/lentes#2]
In an app I'm currently developing I found a use cases where it would be beneficial if I could check if two lenses are the same. Currently this is only possible by using deref and compare  the values (and that does not guarantee the lenses are pointing at the same location in a datastructure)

would it be possible to implement IEquiv, e.g. by comparing the id of the lens?

**Comment by niwinz** [comment]
Hi @sj4 

The question here is, that it means the two focuses are the same? The response can be:
- Points to the same location as the other (pretty imposible to implement due to the design of lenses composition, because it is simple function composition).
- The value of two lenses is the same (it posible but maybe is not that you want)
- The lense is identical to other (in this case we don't need check for id equality, it just can be checked with `identical?` predicate.

Maybe I'm missing something, but I don't find where the `IEquiv` can be useful for focuses, can you elaborate more please!

**Comment by sj4** [comment]
Hi, thanks for your quick reply.
I was refering to the third case, but didn't think of using `identical?`. Thanks for the hint :)
However, when I try the following:
```clojure
(def x (l/derive (l/key :some-key) some-atom))
(def y (l/derive (l/key :some-key) some-atom))
(js/console.log (identical? x y))
```
I expected/hoped to get `true` as output, but I get `false`...

**Comment by ghost** [comment]
I think using `identical?` should solve the case, thanks for the hint, sorry for the noise

**Comment by niwinz** [comment]
No problem ;)
